version: "3.2"

services:

  webserver:
    build:
      context: ./docker/web
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
    networks:
      - web

networks:
  web:
    driver: bridge


  

